name: 'utils'

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /docker/apps/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'

  organizr:
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/apps/organizr:/config
    ports:
      - '80:80'
    cap_add:
      - NET_BIND_SERVICE

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_RAW
      - SETUID

  zerotier:
    image: zerotier/zerotier:latest
    restart: unless-stopped
    volumes:
      - /docker/apps/zerotier:/var/lib/zerotier-one
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    network_mode: host

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/apps/librespeed:/config
    ports:
      - '9091:80'

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /docker/apps/homarr/configs:/app/data/configs
      - /docker/apps/homarr/icons:/app/public/icons
      - /docker/apps/homarr/data:/data
    ports:
      - '7575:7575'

  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /docker/apps/filezilla:/config
      - /data/Videos/USB:/USB
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /data:/srv
      - /docker/apps/filebrowser:/database/filebrowser.db
      - /docker/apps/filebrowser:/config/settings.json
    ports:
      - 8888:80
    restart: unless-stopped